created = 2026-09-25T08:25:19.000Z
kind = "report"
project = "afa96d7e-4e77-4a09-a7af-73dc5c56e7ca"
spec = "registry/2"
title = "Kondo screening in the symmetric Anderson model: NRG thermodynamics across U/Γ"
uuid = "2a55ada6-d482-4566-aca7-fb4ce8dc0197"
