[assets_figures_logistic_bifurcation_bifurcation_fig1]
key = "4301018468512878832"
assets = ["assets/figures/logistic/bifurcation/bifurcation_fig1.svg"]

[assets_figures_logistic_orbits_orbits_fig1]
key = "11255202992012926054"
assets = ["assets/figures/logistic/orbits/orbits_fig1.svg"]

[assets_figures_oscillator_decay_decay_fig1]
key = "9084321594639379599"
assets = ["assets/figures/oscillator/decay/decay_fig1.svg"]
