[assets_figures_logistic_bifurcation_bifurcation_fig1]
key = "15929935394498406650"
assets = ["assets/figures/logistic/bifurcation/bifurcation_fig1.png"]

[assets_figures_logistic_orbits_orbits_fig1]
key = "15104781759722964145"
assets = ["assets/figures/logistic/orbits/orbits_fig1.svg", "assets/figures/logistic/orbits/orbits_fig1.csv"]

[assets_figures_oscillator_decay_decay_fig1]
key = "14553712531605070024"
assets = ["assets/figures/oscillator/decay/decay_fig1.svg", "assets/figures/oscillator/decay/decay_fig1.csv"]
